image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: C:\Python35
      QT_API: PyQt5
    - PYTHON: C:\Python35-x64
      QT_API: PySide2
    - PYTHON: C:\Python36
      QT_API: PySide2
    - PYTHON: C:\Python36-x64
      QT_API: PySide6
    - PYTHON: C:\Python37
      QT_API: PyQt5
    - PYTHON: C:\Python37-x64
      QT_API: PySide6
    - PYTHON: C:\Python38
      QT_API: PySide2
    - PYTHON: C:\Python38-x64
      QT_API: PySide6
    - PYTHON: C:\Python39
      QT_API: PySide2
      CLONE_PYTHONNET: "true"
    - PYTHON: C:\Python39-x64
      QT_API: PySide6
      CLONE_PYTHONNET: "true"
    - PYTHON: C:\Python39-x64
      QT_API: PyQt6
      CLONE_PYTHONNET: "true"
    - PYTHON: C:\Python39-x64
      QT_API: PySide2
      CLONE_PYTHONNET: "true"
    - PYTHON: C:\Python39-x64
      QT_API: PyQt5
      CLONE_PYTHONNET: "true"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools wheel
  - python -m pip install --upgrade pytest pytest-cov pytest-runner jedi pycodestyle pyflakes
  - python -m pip install %QT_API%
  - IF "%CLONE_PYTHONNET%"=="true" (
      python -m pip install --upgrade pycparser &&
      python -m pip install git+https://github.com/pythonnet/pythonnet.git
    ) ELSE (
      python -m pip install --upgrade pythonnet
    )
  - python -m pip list

build: off

test_script:
  - python -c "from msl import qt; print(qt.binding)"
  - python -m pytest

after_test:
  - python setup.py sdist bdist_wheel

artifacts:
  - path: dist\*
