dist: focal  # https://docs.travis-ci.com/user/reference/linux
language: python
sudo: required

os: osx
osx_image: xcode12.2  # https://docs.travis-ci.com/user/reference/osx/#macos-version

jobs:
  include:
    - os: linux
      python: 3.5
      env: QT_API=PySide2
    - os: linux
      python: 3.6
      env: QT_API=PySide6
    - os: linux
      python: 3.7
      env: QT_API=PySide6
    - os: linux
      python: 3.8
      env: QT_API=PySide6
    - os: linux
      python: 3.9
      env: QT_API=PySide6
    - os: linux
      python: 3.9
      env: QT_API=PySide2
    - os: linux
      python: 3.9
      env: QT_API=PyQt6
    - os: linux
      python: 3.9
      env: QT_API=PyQt5
    - os: osx
      language: shell
      env: PYTHON=3.5.10 QT_API=PySide2
    - os: osx
      language: shell
      env: PYTHON=3.6.12 QT_API=PySide6
    - os: osx
      language: shell
      env: PYTHON=3.7.9 QT_API=PySide6
    - os: osx
      language: shell
      env: PYTHON=3.8.6 QT_API=PySide6
    - os: osx
      language: shell
      env: PYTHON=3.9.0 QT_API=PySide6

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      brew outdated pyenv || brew upgrade pyenv
      pyenv --version
      echo "Available Python versions:"
      pyenv install --list | grep "^\s*\d"
      pyenv install $PYTHON
      export PYENV_VERSION=$PYTHON
      export PATH="/Users/travis/.pyenv/versions/$PYTHON/bin:$PATH"
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt update
      sudo apt install -y xvfb herbstluftwm libdbus-1-3 libxkbcommon-x11-0 libglvnd-dev
      sudo apt install -y libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0
      export DISPLAY=:99.0
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
      sleep 3
    fi

install:
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools wheel
  - python -m pip install --upgrade pytest pytest-cov pytest-runner jedi pycodestyle pyflakes
  - python -m pip install --upgrade $QT_API
  - python -m pip list

before_script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      herbstluftwm &
      sleep 1
    fi

script:
  - python -c "from msl import qt; print(qt.binding)"
  - python -m pytest
