language: python

dist: xenial

sudo: required

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: osx
      language: generic
      env: PYTHON=3.5.9
    - os: osx
      language: generic
      env: PYTHON=3.6.10
    - os: osx
      language: generic
      env: PYTHON=3.7.6
    - os: osx
      language: generic
      env: PYTHON=3.8.1

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      brew outdated pyenv || brew upgrade pyenv
      brew install pyenv-virtualenv
      pyenv install --list
      pyenv install $PYTHON
      export PYENV_VERSION=$PYTHON
      pyenv virtualenv venv
      source /Users/travis/.pyenv/versions/${PYTHON}/envs/venv/bin/activate
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt update
      sudo apt install libdbus-1-3 libxkbcommon-x11-0 -y
    fi

install:
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools wheel
  - python -m pip install PySide2
  - python -c "from PySide2.QtWidgets import QApplication; QApplication([])"

script:
  - python setup.py tests
