import pytest

from msl.qt import Qt
from msl.qt import QtGui
from msl.qt import QtWidgets
from msl.qt import binding


@pytest.mark.parametrize('style', (QtWidgets.QStyle, QtWidgets.QCommonStyle))
def test_qstyle(style):
    assert style.StateFlag.State_None == style.State_None
    assert style.StateFlag.State_Active == style.State_Active
    assert style.StateFlag.State_AutoRaise == style.State_AutoRaise
    assert style.StateFlag.State_Children == style.State_Children
    assert style.StateFlag.State_DownArrow == style.State_DownArrow
    assert style.StateFlag.State_Editing == style.State_Editing
    assert style.StateFlag.State_Enabled == style.State_Enabled
    #  assert style.StateFlag.State_HasEditFocus == style.State_HasEditFocus
    assert style.StateFlag.State_HasFocus == style.State_HasFocus
    assert style.StateFlag.State_Horizontal == style.State_Horizontal
    assert style.StateFlag.State_KeyboardFocusChange == style.State_KeyboardFocusChange
    assert style.StateFlag.State_MouseOver == style.State_MouseOver
    assert style.StateFlag.State_NoChange == style.State_NoChange
    assert style.StateFlag.State_Off == style.State_Off
    assert style.StateFlag.State_On == style.State_On
    assert style.StateFlag.State_Raised == style.State_Raised
    assert style.StateFlag.State_ReadOnly == style.State_ReadOnly
    assert style.StateFlag.State_Selected == style.State_Selected
    assert style.StateFlag.State_Item == style.State_Item
    assert style.StateFlag.State_Open == style.State_Open
    assert style.StateFlag.State_Sibling == style.State_Sibling
    assert style.StateFlag.State_Sunken == style.State_Sunken
    assert style.StateFlag.State_UpArrow == style.State_UpArrow
    assert style.StateFlag.State_Mini == style.State_Mini
    assert style.StateFlag.State_Small == style.State_Small

    assert style.SubControl.SC_None == style.SC_None
    assert style.SubControl.SC_ScrollBarAddLine == style.SC_ScrollBarAddLine
    assert style.SubControl.SC_ScrollBarSubLine == style.SC_ScrollBarSubLine
    assert style.SubControl.SC_ScrollBarAddPage == style.SC_ScrollBarAddPage
    assert style.SubControl.SC_ScrollBarSubPage == style.SC_ScrollBarSubPage
    assert style.SubControl.SC_ScrollBarFirst == style.SC_ScrollBarFirst
    assert style.SubControl.SC_ScrollBarLast == style.SC_ScrollBarLast
    assert style.SubControl.SC_ScrollBarSlider == style.SC_ScrollBarSlider
    assert style.SubControl.SC_ScrollBarGroove == style.SC_ScrollBarGroove
    assert style.SubControl.SC_SpinBoxUp == style.SC_SpinBoxUp
    assert style.SubControl.SC_SpinBoxDown == style.SC_SpinBoxDown
    assert style.SubControl.SC_SpinBoxFrame == style.SC_SpinBoxFrame
    assert style.SubControl.SC_SpinBoxEditField == style.SC_SpinBoxEditField
    assert style.SubControl.SC_ComboBoxEditField == style.SC_ComboBoxEditField
    assert style.SubControl.SC_ComboBoxArrow == style.SC_ComboBoxArrow
    assert style.SubControl.SC_ComboBoxFrame == style.SC_ComboBoxFrame
    assert style.SubControl.SC_ComboBoxListBoxPopup == style.SC_ComboBoxListBoxPopup
    assert style.SubControl.SC_SliderGroove == style.SC_SliderGroove
    assert style.SubControl.SC_SliderHandle == style.SC_SliderHandle
    assert style.SubControl.SC_SliderTickmarks == style.SC_SliderTickmarks
    assert style.SubControl.SC_ToolButton == style.SC_ToolButton
    assert style.SubControl.SC_ToolButtonMenu == style.SC_ToolButtonMenu
    assert style.SubControl.SC_TitleBarSysMenu == style.SC_TitleBarSysMenu
    assert style.SubControl.SC_TitleBarMinButton == style.SC_TitleBarMinButton
    assert style.SubControl.SC_TitleBarMaxButton == style.SC_TitleBarMaxButton
    assert style.SubControl.SC_TitleBarCloseButton == style.SC_TitleBarCloseButton
    assert style.SubControl.SC_TitleBarLabel == style.SC_TitleBarLabel
    assert style.SubControl.SC_TitleBarNormalButton == style.SC_TitleBarNormalButton
    assert style.SubControl.SC_TitleBarShadeButton == style.SC_TitleBarShadeButton
    assert style.SubControl.SC_TitleBarUnshadeButton == style.SC_TitleBarUnshadeButton
    assert style.SubControl.SC_TitleBarContextHelpButton == style.SC_TitleBarContextHelpButton
    assert style.SubControl.SC_DialHandle == style.SC_DialHandle
    assert style.SubControl.SC_DialGroove == style.SC_DialGroove
    assert style.SubControl.SC_DialTickmarks == style.SC_DialTickmarks
    assert style.SubControl.SC_GroupBoxFrame == style.SC_GroupBoxFrame
    assert style.SubControl.SC_GroupBoxLabel == style.SC_GroupBoxLabel
    assert style.SubControl.SC_GroupBoxCheckBox == style.SC_GroupBoxCheckBox
    assert style.SubControl.SC_GroupBoxContents == style.SC_GroupBoxContents
    assert style.SubControl.SC_MdiNormalButton == style.SC_MdiNormalButton
    assert style.SubControl.SC_MdiMinButton == style.SC_MdiMinButton
    assert style.SubControl.SC_MdiCloseButton == style.SC_MdiCloseButton
    assert style.SubControl.SC_All == style.SC_All

    assert style.PrimitiveElement.PE_PanelButtonCommand == style.PE_PanelButtonCommand
    assert style.PrimitiveElement.PE_FrameDefaultButton == style.PE_FrameDefaultButton
    assert style.PrimitiveElement.PE_PanelButtonBevel == style.PE_PanelButtonBevel
    assert style.PrimitiveElement.PE_PanelButtonTool == style.PE_PanelButtonTool
    assert style.PrimitiveElement.PE_PanelLineEdit == style.PE_PanelLineEdit
    assert style.PrimitiveElement.PE_IndicatorButtonDropDown == style.PE_IndicatorButtonDropDown
    assert style.PrimitiveElement.PE_FrameFocusRect == style.PE_FrameFocusRect
    assert style.PrimitiveElement.PE_IndicatorArrowUp == style.PE_IndicatorArrowUp
    assert style.PrimitiveElement.PE_IndicatorArrowDown == style.PE_IndicatorArrowDown
    assert style.PrimitiveElement.PE_IndicatorArrowRight == style.PE_IndicatorArrowRight
    assert style.PrimitiveElement.PE_IndicatorArrowLeft == style.PE_IndicatorArrowLeft
    assert style.PrimitiveElement.PE_IndicatorSpinUp == style.PE_IndicatorSpinUp
    assert style.PrimitiveElement.PE_IndicatorSpinDown == style.PE_IndicatorSpinDown
    assert style.PrimitiveElement.PE_IndicatorSpinPlus == style.PE_IndicatorSpinPlus
    assert style.PrimitiveElement.PE_IndicatorSpinMinus == style.PE_IndicatorSpinMinus
    assert style.PrimitiveElement.PE_IndicatorItemViewItemCheck == style.PE_IndicatorItemViewItemCheck
    assert style.PrimitiveElement.PE_IndicatorCheckBox == style.PE_IndicatorCheckBox
    assert style.PrimitiveElement.PE_IndicatorRadioButton == style.PE_IndicatorRadioButton
    assert style.PrimitiveElement.PE_IndicatorDockWidgetResizeHandle == style.PE_IndicatorDockWidgetResizeHandle
    assert style.PrimitiveElement.PE_Frame == style.PE_Frame
    assert style.PrimitiveElement.PE_FrameMenu == style.PE_FrameMenu
    assert style.PrimitiveElement.PE_PanelMenuBar == style.PE_PanelMenuBar
    assert style.PrimitiveElement.PE_PanelScrollAreaCorner == style.PE_PanelScrollAreaCorner
    assert style.PrimitiveElement.PE_FrameDockWidget == style.PE_FrameDockWidget
    assert style.PrimitiveElement.PE_FrameTabWidget == style.PE_FrameTabWidget
    assert style.PrimitiveElement.PE_FrameLineEdit == style.PE_FrameLineEdit
    assert style.PrimitiveElement.PE_FrameGroupBox == style.PE_FrameGroupBox
    assert style.PrimitiveElement.PE_FrameButtonBevel == style.PE_FrameButtonBevel
    assert style.PrimitiveElement.PE_FrameButtonTool == style.PE_FrameButtonTool
    assert style.PrimitiveElement.PE_IndicatorHeaderArrow == style.PE_IndicatorHeaderArrow
    assert style.PrimitiveElement.PE_FrameStatusBarItem == style.PE_FrameStatusBarItem
    assert style.PrimitiveElement.PE_FrameWindow == style.PE_FrameWindow
    assert style.PrimitiveElement.PE_IndicatorMenuCheckMark == style.PE_IndicatorMenuCheckMark
    assert style.PrimitiveElement.PE_IndicatorProgressChunk == style.PE_IndicatorProgressChunk
    assert style.PrimitiveElement.PE_IndicatorBranch == style.PE_IndicatorBranch
    assert style.PrimitiveElement.PE_IndicatorToolBarHandle == style.PE_IndicatorToolBarHandle
    assert style.PrimitiveElement.PE_IndicatorToolBarSeparator == style.PE_IndicatorToolBarSeparator
    assert style.PrimitiveElement.PE_PanelToolBar == style.PE_PanelToolBar
    assert style.PrimitiveElement.PE_PanelTipLabel == style.PE_PanelTipLabel
    assert style.PrimitiveElement.PE_FrameTabBarBase == style.PE_FrameTabBarBase
    assert style.PrimitiveElement.PE_IndicatorTabTear == style.PE_IndicatorTabTear
    assert style.PrimitiveElement.PE_IndicatorTabTearLeft == style.PE_IndicatorTabTearLeft
    assert style.PrimitiveElement.PE_IndicatorTabTearRight == style.PE_IndicatorTabTearRight
    assert style.PrimitiveElement.PE_IndicatorColumnViewArrow == style.PE_IndicatorColumnViewArrow
    assert style.PrimitiveElement.PE_Widget == style.PE_Widget
    assert style.PrimitiveElement.PE_CustomBase == style.PE_CustomBase
    assert style.PrimitiveElement.PE_IndicatorItemViewItemDrop == style.PE_IndicatorItemViewItemDrop
    assert style.PrimitiveElement.PE_PanelItemViewItem == style.PE_PanelItemViewItem
    assert style.PrimitiveElement.PE_PanelItemViewRow == style.PE_PanelItemViewRow
    assert style.PrimitiveElement.PE_PanelStatusBar == style.PE_PanelStatusBar
    assert style.PrimitiveElement.PE_IndicatorTabClose == style.PE_IndicatorTabClose
    assert style.PrimitiveElement.PE_PanelMenu == style.PE_PanelMenu

    assert style.ControlElement.CE_PushButton == style.CE_PushButton
    assert style.ControlElement.CE_PushButtonBevel == style.CE_PushButtonBevel
    assert style.ControlElement.CE_PushButtonLabel == style.CE_PushButtonLabel
    assert style.ControlElement.CE_DockWidgetTitle == style.CE_DockWidgetTitle
    assert style.ControlElement.CE_Splitter == style.CE_Splitter
    assert style.ControlElement.CE_CheckBox == style.CE_CheckBox
    assert style.ControlElement.CE_CheckBoxLabel == style.CE_CheckBoxLabel
    assert style.ControlElement.CE_RadioButton == style.CE_RadioButton
    assert style.ControlElement.CE_RadioButtonLabel == style.CE_RadioButtonLabel
    assert style.ControlElement.CE_TabBarTab == style.CE_TabBarTab
    assert style.ControlElement.CE_TabBarTabShape == style.CE_TabBarTabShape
    assert style.ControlElement.CE_TabBarTabLabel == style.CE_TabBarTabLabel
    assert style.ControlElement.CE_ProgressBar == style.CE_ProgressBar
    assert style.ControlElement.CE_ProgressBarGroove == style.CE_ProgressBarGroove
    assert style.ControlElement.CE_ProgressBarContents == style.CE_ProgressBarContents
    assert style.ControlElement.CE_ProgressBarLabel == style.CE_ProgressBarLabel
    assert style.ControlElement.CE_ToolButtonLabel == style.CE_ToolButtonLabel
    assert style.ControlElement.CE_MenuBarItem == style.CE_MenuBarItem
    assert style.ControlElement.CE_MenuBarEmptyArea == style.CE_MenuBarEmptyArea
    assert style.ControlElement.CE_MenuItem == style.CE_MenuItem
    assert style.ControlElement.CE_MenuScroller == style.CE_MenuScroller
    assert style.ControlElement.CE_MenuTearoff == style.CE_MenuTearoff
    assert style.ControlElement.CE_MenuEmptyArea == style.CE_MenuEmptyArea
    assert style.ControlElement.CE_MenuHMargin == style.CE_MenuHMargin
    assert style.ControlElement.CE_MenuVMargin == style.CE_MenuVMargin
    assert style.ControlElement.CE_ToolBoxTab == style.CE_ToolBoxTab
    assert style.ControlElement.CE_SizeGrip == style.CE_SizeGrip
    assert style.ControlElement.CE_Header == style.CE_Header
    assert style.ControlElement.CE_HeaderSection == style.CE_HeaderSection
    assert style.ControlElement.CE_HeaderLabel == style.CE_HeaderLabel
    assert style.ControlElement.CE_ScrollBarAddLine == style.CE_ScrollBarAddLine
    assert style.ControlElement.CE_ScrollBarSubLine == style.CE_ScrollBarSubLine
    assert style.ControlElement.CE_ScrollBarAddPage == style.CE_ScrollBarAddPage
    assert style.ControlElement.CE_ScrollBarSubPage == style.CE_ScrollBarSubPage
    assert style.ControlElement.CE_ScrollBarSlider == style.CE_ScrollBarSlider
    assert style.ControlElement.CE_ScrollBarFirst == style.CE_ScrollBarFirst
    assert style.ControlElement.CE_ScrollBarLast == style.CE_ScrollBarLast
    assert style.ControlElement.CE_RubberBand == style.CE_RubberBand
    assert style.ControlElement.CE_FocusFrame == style.CE_FocusFrame
    assert style.ControlElement.CE_ItemViewItem == style.CE_ItemViewItem
    assert style.ControlElement.CE_CustomBase == style.CE_CustomBase
    assert style.ControlElement.CE_ComboBoxLabel == style.CE_ComboBoxLabel
    assert style.ControlElement.CE_ToolBar == style.CE_ToolBar
    assert style.ControlElement.CE_ToolBoxTabShape == style.CE_ToolBoxTabShape
    assert style.ControlElement.CE_ToolBoxTabLabel == style.CE_ToolBoxTabLabel
    assert style.ControlElement.CE_HeaderEmptyArea == style.CE_HeaderEmptyArea
    assert style.ControlElement.CE_ShapedFrame == style.CE_ShapedFrame

    assert style.SubElement.SE_PushButtonContents == style.SE_PushButtonContents
    assert style.SubElement.SE_PushButtonFocusRect == style.SE_PushButtonFocusRect
    assert style.SubElement.SE_PushButtonLayoutItem == style.SE_PushButtonLayoutItem
    assert style.SubElement.SE_PushButtonBevel == style.SE_PushButtonBevel
    assert style.SubElement.SE_CheckBoxIndicator == style.SE_CheckBoxIndicator
    assert style.SubElement.SE_CheckBoxContents == style.SE_CheckBoxContents
    assert style.SubElement.SE_CheckBoxFocusRect == style.SE_CheckBoxFocusRect
    assert style.SubElement.SE_CheckBoxClickRect == style.SE_CheckBoxClickRect
    assert style.SubElement.SE_CheckBoxLayoutItem == style.SE_CheckBoxLayoutItem
    assert style.SubElement.SE_DateTimeEditLayoutItem == style.SE_DateTimeEditLayoutItem
    assert style.SubElement.SE_RadioButtonIndicator == style.SE_RadioButtonIndicator
    assert style.SubElement.SE_RadioButtonContents == style.SE_RadioButtonContents
    assert style.SubElement.SE_RadioButtonFocusRect == style.SE_RadioButtonFocusRect
    assert style.SubElement.SE_RadioButtonClickRect == style.SE_RadioButtonClickRect
    assert style.SubElement.SE_RadioButtonLayoutItem == style.SE_RadioButtonLayoutItem
    assert style.SubElement.SE_ComboBoxFocusRect == style.SE_ComboBoxFocusRect
    assert style.SubElement.SE_SliderFocusRect == style.SE_SliderFocusRect
    assert style.SubElement.SE_SliderLayoutItem == style.SE_SliderLayoutItem
    assert style.SubElement.SE_SpinBoxLayoutItem == style.SE_SpinBoxLayoutItem
    assert style.SubElement.SE_ProgressBarGroove == style.SE_ProgressBarGroove
    assert style.SubElement.SE_ProgressBarContents == style.SE_ProgressBarContents
    assert style.SubElement.SE_ProgressBarLabel == style.SE_ProgressBarLabel
    assert style.SubElement.SE_ProgressBarLayoutItem == style.SE_ProgressBarLayoutItem
    assert style.SubElement.SE_FrameContents == style.SE_FrameContents
    assert style.SubElement.SE_ShapedFrameContents == style.SE_ShapedFrameContents
    assert style.SubElement.SE_FrameLayoutItem == style.SE_FrameLayoutItem
    assert style.SubElement.SE_HeaderArrow == style.SE_HeaderArrow
    assert style.SubElement.SE_HeaderLabel == style.SE_HeaderLabel
    assert style.SubElement.SE_LabelLayoutItem == style.SE_LabelLayoutItem
    assert style.SubElement.SE_LineEditContents == style.SE_LineEditContents
    assert style.SubElement.SE_TabWidgetLeftCorner == style.SE_TabWidgetLeftCorner
    assert style.SubElement.SE_TabWidgetRightCorner == style.SE_TabWidgetRightCorner
    assert style.SubElement.SE_TabWidgetTabBar == style.SE_TabWidgetTabBar
    assert style.SubElement.SE_TabWidgetTabContents == style.SE_TabWidgetTabContents
    assert style.SubElement.SE_TabWidgetTabPane == style.SE_TabWidgetTabPane
    assert style.SubElement.SE_TabWidgetLayoutItem == style.SE_TabWidgetLayoutItem
    assert style.SubElement.SE_ToolBoxTabContents == style.SE_ToolBoxTabContents
    assert style.SubElement.SE_ToolButtonLayoutItem == style.SE_ToolButtonLayoutItem
    assert style.SubElement.SE_ItemViewItemCheckIndicator == style.SE_ItemViewItemCheckIndicator
    assert style.SubElement.SE_TabBarTearIndicator == style.SE_TabBarTearIndicator
    assert style.SubElement.SE_TabBarTearIndicatorLeft == style.SE_TabBarTearIndicatorLeft
    assert style.SubElement.SE_TabBarTearIndicatorRight == style.SE_TabBarTearIndicatorRight
    assert style.SubElement.SE_TabBarScrollLeftButton == style.SE_TabBarScrollLeftButton
    assert style.SubElement.SE_TabBarScrollRightButton == style.SE_TabBarScrollRightButton
    assert style.SubElement.SE_TreeViewDisclosureItem == style.SE_TreeViewDisclosureItem
    assert style.SubElement.SE_GroupBoxLayoutItem == style.SE_GroupBoxLayoutItem
    assert style.SubElement.SE_CustomBase == style.SE_CustomBase
    assert style.SubElement.SE_DockWidgetFloatButton == style.SE_DockWidgetFloatButton
    assert style.SubElement.SE_DockWidgetTitleBarText == style.SE_DockWidgetTitleBarText
    assert style.SubElement.SE_DockWidgetCloseButton == style.SE_DockWidgetCloseButton
    assert style.SubElement.SE_DockWidgetIcon == style.SE_DockWidgetIcon
    assert style.SubElement.SE_ComboBoxLayoutItem == style.SE_ComboBoxLayoutItem
    assert style.SubElement.SE_ItemViewItemDecoration == style.SE_ItemViewItemDecoration
    assert style.SubElement.SE_ItemViewItemText == style.SE_ItemViewItemText
    assert style.SubElement.SE_ItemViewItemFocusRect == style.SE_ItemViewItemFocusRect
    assert style.SubElement.SE_TabBarTabLeftButton == style.SE_TabBarTabLeftButton
    assert style.SubElement.SE_TabBarTabRightButton == style.SE_TabBarTabRightButton
    assert style.SubElement.SE_TabBarTabText == style.SE_TabBarTabText
    assert style.SubElement.SE_ToolBarHandle == style.SE_ToolBarHandle

    assert style.ComplexControl.CC_SpinBox == style.CC_SpinBox
    assert style.ComplexControl.CC_ComboBox == style.CC_ComboBox
    assert style.ComplexControl.CC_ScrollBar == style.CC_ScrollBar
    assert style.ComplexControl.CC_Slider == style.CC_Slider
    assert style.ComplexControl.CC_ToolButton == style.CC_ToolButton
    assert style.ComplexControl.CC_TitleBar == style.CC_TitleBar
    assert style.ComplexControl.CC_GroupBox == style.CC_GroupBox
    assert style.ComplexControl.CC_Dial == style.CC_Dial
    assert style.ComplexControl.CC_MdiControls == style.CC_MdiControls
    assert style.ComplexControl.CC_CustomBase == style.CC_CustomBase

    assert style.PixelMetric.PM_ButtonMargin == style.PM_ButtonMargin
    assert style.PixelMetric.PM_DockWidgetTitleBarButtonMargin == style.PM_DockWidgetTitleBarButtonMargin
    assert style.PixelMetric.PM_ButtonDefaultIndicator == style.PM_ButtonDefaultIndicator
    assert style.PixelMetric.PM_MenuButtonIndicator == style.PM_MenuButtonIndicator
    assert style.PixelMetric.PM_ButtonShiftHorizontal == style.PM_ButtonShiftHorizontal
    assert style.PixelMetric.PM_ButtonShiftVertical == style.PM_ButtonShiftVertical
    assert style.PixelMetric.PM_DefaultFrameWidth == style.PM_DefaultFrameWidth
    assert style.PixelMetric.PM_SpinBoxFrameWidth == style.PM_SpinBoxFrameWidth
    assert style.PixelMetric.PM_ComboBoxFrameWidth == style.PM_ComboBoxFrameWidth
    assert style.PixelMetric.PM_MdiSubWindowFrameWidth == style.PM_MdiSubWindowFrameWidth
    assert style.PixelMetric.PM_MdiSubWindowMinimizedWidth == style.PM_MdiSubWindowMinimizedWidth
    assert style.PixelMetric.PM_LayoutLeftMargin == style.PM_LayoutLeftMargin
    assert style.PixelMetric.PM_LayoutTopMargin == style.PM_LayoutTopMargin
    assert style.PixelMetric.PM_LayoutRightMargin == style.PM_LayoutRightMargin
    assert style.PixelMetric.PM_LayoutBottomMargin == style.PM_LayoutBottomMargin
    assert style.PixelMetric.PM_LayoutHorizontalSpacing == style.PM_LayoutHorizontalSpacing
    assert style.PixelMetric.PM_LayoutVerticalSpacing == style.PM_LayoutVerticalSpacing
    assert style.PixelMetric.PM_MaximumDragDistance == style.PM_MaximumDragDistance
    assert style.PixelMetric.PM_ScrollBarExtent == style.PM_ScrollBarExtent
    assert style.PixelMetric.PM_ScrollBarSliderMin == style.PM_ScrollBarSliderMin
    assert style.PixelMetric.PM_SliderThickness == style.PM_SliderThickness
    assert style.PixelMetric.PM_SliderControlThickness == style.PM_SliderControlThickness
    assert style.PixelMetric.PM_SliderLength == style.PM_SliderLength
    assert style.PixelMetric.PM_SliderTickmarkOffset == style.PM_SliderTickmarkOffset
    assert style.PixelMetric.PM_SliderSpaceAvailable == style.PM_SliderSpaceAvailable
    assert style.PixelMetric.PM_DockWidgetSeparatorExtent == style.PM_DockWidgetSeparatorExtent
    assert style.PixelMetric.PM_DockWidgetHandleExtent == style.PM_DockWidgetHandleExtent
    assert style.PixelMetric.PM_DockWidgetFrameWidth == style.PM_DockWidgetFrameWidth
    assert style.PixelMetric.PM_DockWidgetTitleMargin == style.PM_DockWidgetTitleMargin
    assert style.PixelMetric.PM_MenuBarPanelWidth == style.PM_MenuBarPanelWidth
    assert style.PixelMetric.PM_MenuBarItemSpacing == style.PM_MenuBarItemSpacing
    assert style.PixelMetric.PM_MenuBarHMargin == style.PM_MenuBarHMargin
    assert style.PixelMetric.PM_MenuBarVMargin == style.PM_MenuBarVMargin
    assert style.PixelMetric.PM_ToolBarFrameWidth == style.PM_ToolBarFrameWidth
    assert style.PixelMetric.PM_ToolBarHandleExtent == style.PM_ToolBarHandleExtent
    assert style.PixelMetric.PM_ToolBarItemMargin == style.PM_ToolBarItemMargin
    assert style.PixelMetric.PM_ToolBarItemSpacing == style.PM_ToolBarItemSpacing
    assert style.PixelMetric.PM_ToolBarSeparatorExtent == style.PM_ToolBarSeparatorExtent
    assert style.PixelMetric.PM_ToolBarExtensionExtent == style.PM_ToolBarExtensionExtent
    assert style.PixelMetric.PM_TabBarTabOverlap == style.PM_TabBarTabOverlap
    assert style.PixelMetric.PM_TabBarTabHSpace == style.PM_TabBarTabHSpace
    assert style.PixelMetric.PM_TabBarTabVSpace == style.PM_TabBarTabVSpace
    assert style.PixelMetric.PM_TabBarBaseHeight == style.PM_TabBarBaseHeight
    assert style.PixelMetric.PM_TabBarBaseOverlap == style.PM_TabBarBaseOverlap
    assert style.PixelMetric.PM_TabBarScrollButtonWidth == style.PM_TabBarScrollButtonWidth
    assert style.PixelMetric.PM_TabBarTabShiftHorizontal == style.PM_TabBarTabShiftHorizontal
    assert style.PixelMetric.PM_TabBarTabShiftVertical == style.PM_TabBarTabShiftVertical
    assert style.PixelMetric.PM_ProgressBarChunkWidth == style.PM_ProgressBarChunkWidth
    assert style.PixelMetric.PM_SplitterWidth == style.PM_SplitterWidth
    assert style.PixelMetric.PM_TitleBarHeight == style.PM_TitleBarHeight
    assert style.PixelMetric.PM_IndicatorWidth == style.PM_IndicatorWidth
    assert style.PixelMetric.PM_IndicatorHeight == style.PM_IndicatorHeight
    assert style.PixelMetric.PM_ExclusiveIndicatorWidth == style.PM_ExclusiveIndicatorWidth
    assert style.PixelMetric.PM_ExclusiveIndicatorHeight == style.PM_ExclusiveIndicatorHeight
    assert style.PixelMetric.PM_MenuPanelWidth == style.PM_MenuPanelWidth
    assert style.PixelMetric.PM_MenuHMargin == style.PM_MenuHMargin
    assert style.PixelMetric.PM_MenuVMargin == style.PM_MenuVMargin
    assert style.PixelMetric.PM_MenuScrollerHeight == style.PM_MenuScrollerHeight
    assert style.PixelMetric.PM_MenuTearoffHeight == style.PM_MenuTearoffHeight
    assert style.PixelMetric.PM_MenuDesktopFrameWidth == style.PM_MenuDesktopFrameWidth
    assert style.PixelMetric.PM_HeaderMarkSize == style.PM_HeaderMarkSize
    assert style.PixelMetric.PM_HeaderGripMargin == style.PM_HeaderGripMargin
    assert style.PixelMetric.PM_HeaderMargin == style.PM_HeaderMargin
    assert style.PixelMetric.PM_SpinBoxSliderHeight == style.PM_SpinBoxSliderHeight
    assert style.PixelMetric.PM_ToolBarIconSize == style.PM_ToolBarIconSize
    assert style.PixelMetric.PM_SmallIconSize == style.PM_SmallIconSize
    assert style.PixelMetric.PM_LargeIconSize == style.PM_LargeIconSize
    assert style.PixelMetric.PM_FocusFrameHMargin == style.PM_FocusFrameHMargin
    assert style.PixelMetric.PM_FocusFrameVMargin == style.PM_FocusFrameVMargin
    assert style.PixelMetric.PM_IconViewIconSize == style.PM_IconViewIconSize
    assert style.PixelMetric.PM_ListViewIconSize == style.PM_ListViewIconSize
    assert style.PixelMetric.PM_ToolTipLabelFrameWidth == style.PM_ToolTipLabelFrameWidth
    assert style.PixelMetric.PM_CheckBoxLabelSpacing == style.PM_CheckBoxLabelSpacing
    assert style.PixelMetric.PM_RadioButtonLabelSpacing == style.PM_RadioButtonLabelSpacing
    assert style.PixelMetric.PM_TabBarIconSize == style.PM_TabBarIconSize
    assert style.PixelMetric.PM_SizeGripSize == style.PM_SizeGripSize
    assert style.PixelMetric.PM_MessageBoxIconSize == style.PM_MessageBoxIconSize
    assert style.PixelMetric.PM_ButtonIconSize == style.PM_ButtonIconSize
    assert style.PixelMetric.PM_TextCursorWidth == style.PM_TextCursorWidth
    assert style.PixelMetric.PM_TabBar_ScrollButtonOverlap == style.PM_TabBar_ScrollButtonOverlap
    assert style.PixelMetric.PM_TabCloseIndicatorWidth == style.PM_TabCloseIndicatorWidth
    assert style.PixelMetric.PM_TabCloseIndicatorHeight == style.PM_TabCloseIndicatorHeight
    assert style.PixelMetric.PM_ScrollView_ScrollBarSpacing == style.PM_ScrollView_ScrollBarSpacing
    assert style.PixelMetric.PM_ScrollView_ScrollBarOverlap == style.PM_ScrollView_ScrollBarOverlap
    assert style.PixelMetric.PM_SubMenuOverlap == style.PM_SubMenuOverlap
    assert style.PixelMetric.PM_TreeViewIndentation == style.PM_TreeViewIndentation
    assert style.PixelMetric.PM_HeaderDefaultSectionSizeHorizontal == style.PM_HeaderDefaultSectionSizeHorizontal
    assert style.PixelMetric.PM_HeaderDefaultSectionSizeVertical == style.PM_HeaderDefaultSectionSizeVertical
    assert style.PixelMetric.PM_TitleBarButtonIconSize == style.PM_TitleBarButtonIconSize
    assert style.PixelMetric.PM_TitleBarButtonSize == style.PM_TitleBarButtonSize
    if binding.qt_version_info[:2] >= (6, 2):
        assert style.PixelMetric.PM_LineEditIconSize == style.PM_LineEditIconSize
    if binding.qt_version_info[:2] >= (6, 3):
        assert style.PixelMetric.PM_LineEditIconMargin == style.PM_LineEditIconMargin
    assert style.PixelMetric.PM_CustomBase == style.PM_CustomBase

    assert style.ContentsType.CT_CheckBox == style.CT_CheckBox
    assert style.ContentsType.CT_ComboBox == style.CT_ComboBox
    assert style.ContentsType.CT_HeaderSection == style.CT_HeaderSection
    assert style.ContentsType.CT_LineEdit == style.CT_LineEdit
    assert style.ContentsType.CT_Menu == style.CT_Menu
    assert style.ContentsType.CT_MenuBar == style.CT_MenuBar
    assert style.ContentsType.CT_MenuBarItem == style.CT_MenuBarItem
    assert style.ContentsType.CT_MenuItem == style.CT_MenuItem
    assert style.ContentsType.CT_ProgressBar == style.CT_ProgressBar
    assert style.ContentsType.CT_PushButton == style.CT_PushButton
    assert style.ContentsType.CT_RadioButton == style.CT_RadioButton
    assert style.ContentsType.CT_SizeGrip == style.CT_SizeGrip
    assert style.ContentsType.CT_Slider == style.CT_Slider
    assert style.ContentsType.CT_ScrollBar == style.CT_ScrollBar
    assert style.ContentsType.CT_SpinBox == style.CT_SpinBox
    assert style.ContentsType.CT_Splitter == style.CT_Splitter
    assert style.ContentsType.CT_TabBarTab == style.CT_TabBarTab
    assert style.ContentsType.CT_TabWidget == style.CT_TabWidget
    assert style.ContentsType.CT_ToolButton == style.CT_ToolButton
    assert style.ContentsType.CT_GroupBox == style.CT_GroupBox
    assert style.ContentsType.CT_ItemViewItem == style.CT_ItemViewItem
    assert style.ContentsType.CT_CustomBase == style.CT_CustomBase
    assert style.ContentsType.CT_MdiControls == style.CT_MdiControls

    assert style.RequestSoftwareInputPanel.RSIP_OnMouseClickAndAlreadyFocused == style.RSIP_OnMouseClickAndAlreadyFocused
    assert style.RequestSoftwareInputPanel.RSIP_OnMouseClick == style.RSIP_OnMouseClick

    assert style.StyleHint.SH_EtchDisabledText == style.SH_EtchDisabledText
    assert style.StyleHint.SH_DitherDisabledText == style.SH_DitherDisabledText
    assert style.StyleHint.SH_ScrollBar_ContextMenu == style.SH_ScrollBar_ContextMenu
    assert style.StyleHint.SH_ScrollBar_MiddleClickAbsolutePosition == style.SH_ScrollBar_MiddleClickAbsolutePosition
    assert style.StyleHint.SH_ScrollBar_LeftClickAbsolutePosition == style.SH_ScrollBar_LeftClickAbsolutePosition
    assert style.StyleHint.SH_ScrollBar_ScrollWhenPointerLeavesControl == style.SH_ScrollBar_ScrollWhenPointerLeavesControl
    assert style.StyleHint.SH_ScrollBar_RollBetweenButtons == style.SH_ScrollBar_RollBetweenButtons
    assert style.StyleHint.SH_TabBar_Alignment == style.SH_TabBar_Alignment
    assert style.StyleHint.SH_Header_ArrowAlignment == style.SH_Header_ArrowAlignment
    assert style.StyleHint.SH_Slider_SnapToValue == style.SH_Slider_SnapToValue
    assert style.StyleHint.SH_Slider_SloppyKeyEvents == style.SH_Slider_SloppyKeyEvents
    assert style.StyleHint.SH_ProgressDialog_CenterCancelButton == style.SH_ProgressDialog_CenterCancelButton
    assert style.StyleHint.SH_ProgressDialog_TextLabelAlignment == style.SH_ProgressDialog_TextLabelAlignment
    assert style.StyleHint.SH_PrintDialog_RightAlignButtons == style.SH_PrintDialog_RightAlignButtons
    assert style.StyleHint.SH_MainWindow_SpaceBelowMenuBar == style.SH_MainWindow_SpaceBelowMenuBar
    assert style.StyleHint.SH_FontDialog_SelectAssociatedText == style.SH_FontDialog_SelectAssociatedText
    assert style.StyleHint.SH_Menu_KeyboardSearch == style.SH_Menu_KeyboardSearch
    assert style.StyleHint.SH_Menu_AllowActiveAndDisabled == style.SH_Menu_AllowActiveAndDisabled
    assert style.StyleHint.SH_Menu_SpaceActivatesItem == style.SH_Menu_SpaceActivatesItem
    assert style.StyleHint.SH_Menu_SubMenuPopupDelay == style.SH_Menu_SubMenuPopupDelay
    assert style.StyleHint.SH_Menu_Scrollable == style.SH_Menu_Scrollable
    assert style.StyleHint.SH_Menu_SloppySubMenus == style.SH_Menu_SloppySubMenus
    assert style.StyleHint.SH_Menu_SubMenuUniDirection == style.SH_Menu_SubMenuUniDirection
    assert style.StyleHint.SH_Menu_SubMenuUniDirectionFailCount == style.SH_Menu_SubMenuUniDirectionFailCount
    assert style.StyleHint.SH_Menu_SubMenuSloppySelectOtherActions == style.SH_Menu_SubMenuSloppySelectOtherActions
    assert style.StyleHint.SH_Menu_SubMenuSloppyCloseTimeout == style.SH_Menu_SubMenuSloppyCloseTimeout
    assert style.StyleHint.SH_Menu_SubMenuResetWhenReenteringParent == style.SH_Menu_SubMenuResetWhenReenteringParent
    assert style.StyleHint.SH_Menu_SubMenuDontStartSloppyOnLeave == style.SH_Menu_SubMenuDontStartSloppyOnLeave
    assert style.StyleHint.SH_ScrollView_FrameOnlyAroundContents == style.SH_ScrollView_FrameOnlyAroundContents
    assert style.StyleHint.SH_MenuBar_AltKeyNavigation == style.SH_MenuBar_AltKeyNavigation
    assert style.StyleHint.SH_ComboBox_ListMouseTracking == style.SH_ComboBox_ListMouseTracking
    assert style.StyleHint.SH_Menu_MouseTracking == style.SH_Menu_MouseTracking
    assert style.StyleHint.SH_MenuBar_MouseTracking == style.SH_MenuBar_MouseTracking
    assert style.StyleHint.SH_Menu_FillScreenWithScroll == style.SH_Menu_FillScreenWithScroll
    assert style.StyleHint.SH_Menu_SelectionWrap == style.SH_Menu_SelectionWrap
    assert style.StyleHint.SH_ItemView_ChangeHighlightOnFocus == style.SH_ItemView_ChangeHighlightOnFocus
    assert style.StyleHint.SH_Widget_ShareActivation == style.SH_Widget_ShareActivation
    assert style.StyleHint.SH_TabBar_SelectMouseType == style.SH_TabBar_SelectMouseType
    assert style.StyleHint.SH_ListViewExpand_SelectMouseType == style.SH_ListViewExpand_SelectMouseType
    assert style.StyleHint.SH_TabBar_PreferNoArrows == style.SH_TabBar_PreferNoArrows
    assert style.StyleHint.SH_ComboBox_Popup == style.SH_ComboBox_Popup
    assert style.StyleHint.SH_Workspace_FillSpaceOnMaximize == style.SH_Workspace_FillSpaceOnMaximize
    assert style.StyleHint.SH_TitleBar_NoBorder == style.SH_TitleBar_NoBorder
    assert style.StyleHint.SH_Slider_StopMouseOverSlider == style.SH_Slider_StopMouseOverSlider
    assert style.StyleHint.SH_BlinkCursorWhenTextSelected == style.SH_BlinkCursorWhenTextSelected
    assert style.StyleHint.SH_RichText_FullWidthSelection == style.SH_RichText_FullWidthSelection
    assert style.StyleHint.SH_GroupBox_TextLabelVerticalAlignment == style.SH_GroupBox_TextLabelVerticalAlignment
    assert style.StyleHint.SH_GroupBox_TextLabelColor == style.SH_GroupBox_TextLabelColor
    assert style.StyleHint.SH_DialogButtons_DefaultButton == style.SH_DialogButtons_DefaultButton
    assert style.StyleHint.SH_ToolBox_SelectedPageTitleBold == style.SH_ToolBox_SelectedPageTitleBold
    assert style.StyleHint.SH_LineEdit_PasswordCharacter == style.SH_LineEdit_PasswordCharacter
    assert style.StyleHint.SH_LineEdit_PasswordMaskDelay == style.SH_LineEdit_PasswordMaskDelay
    assert style.StyleHint.SH_Table_GridLineColor == style.SH_Table_GridLineColor
    assert style.StyleHint.SH_UnderlineShortcut == style.SH_UnderlineShortcut
    assert style.StyleHint.SH_SpinBox_AnimateButton == style.SH_SpinBox_AnimateButton
    assert style.StyleHint.SH_SpinBox_KeyPressAutoRepeatRate == style.SH_SpinBox_KeyPressAutoRepeatRate
    assert style.StyleHint.SH_SpinBox_ClickAutoRepeatRate == style.SH_SpinBox_ClickAutoRepeatRate
    assert style.StyleHint.SH_SpinBox_ClickAutoRepeatThreshold == style.SH_SpinBox_ClickAutoRepeatThreshold
    if binding.qt_version_info[:2] >= (6, 3):
        assert style.StyleHint.SH_SpinBox_SelectOnStep == style.SH_SpinBox_SelectOnStep
    assert style.StyleHint.SH_ToolTipLabel_Opacity == style.SH_ToolTipLabel_Opacity
    assert style.StyleHint.SH_DrawMenuBarSeparator == style.SH_DrawMenuBarSeparator
    assert style.StyleHint.SH_TitleBar_ModifyNotification == style.SH_TitleBar_ModifyNotification
    assert style.StyleHint.SH_Button_FocusPolicy == style.SH_Button_FocusPolicy
    assert style.StyleHint.SH_CustomBase == style.SH_CustomBase
    assert style.StyleHint.SH_MessageBox_UseBorderForButtonSpacing == style.SH_MessageBox_UseBorderForButtonSpacing
    assert style.StyleHint.SH_MessageBox_CenterButtons == style.SH_MessageBox_CenterButtons
    assert style.StyleHint.SH_MessageBox_TextInteractionFlags == style.SH_MessageBox_TextInteractionFlags
    assert style.StyleHint.SH_TitleBar_AutoRaise == style.SH_TitleBar_AutoRaise
    assert style.StyleHint.SH_ToolButton_PopupDelay == style.SH_ToolButton_PopupDelay
    assert style.StyleHint.SH_FocusFrame_Mask == style.SH_FocusFrame_Mask
    assert style.StyleHint.SH_RubberBand_Mask == style.SH_RubberBand_Mask
    assert style.StyleHint.SH_WindowFrame_Mask == style.SH_WindowFrame_Mask
    assert style.StyleHint.SH_SpinControls_DisableOnBounds == style.SH_SpinControls_DisableOnBounds
    assert style.StyleHint.SH_Dial_BackgroundRole == style.SH_Dial_BackgroundRole
    assert style.StyleHint.SH_ComboBox_LayoutDirection == style.SH_ComboBox_LayoutDirection
    assert style.StyleHint.SH_ItemView_EllipsisLocation == style.SH_ItemView_EllipsisLocation
    assert style.StyleHint.SH_ItemView_ShowDecorationSelected == style.SH_ItemView_ShowDecorationSelected
    assert style.StyleHint.SH_ItemView_ActivateItemOnSingleClick == style.SH_ItemView_ActivateItemOnSingleClick
    assert style.StyleHint.SH_Slider_AbsoluteSetButtons == style.SH_Slider_AbsoluteSetButtons
    assert style.StyleHint.SH_Slider_PageSetButtons == style.SH_Slider_PageSetButtons
    assert style.StyleHint.SH_TabBar_ElideMode == style.SH_TabBar_ElideMode
    assert style.StyleHint.SH_DialogButtonLayout == style.SH_DialogButtonLayout
    assert style.StyleHint.SH_WizardStyle == style.SH_WizardStyle
    assert style.StyleHint.SH_FormLayoutWrapPolicy == style.SH_FormLayoutWrapPolicy
    assert style.StyleHint.SH_FormLayoutFieldGrowthPolicy == style.SH_FormLayoutFieldGrowthPolicy
    assert style.StyleHint.SH_FormLayoutFormAlignment == style.SH_FormLayoutFormAlignment
    assert style.StyleHint.SH_FormLayoutLabelAlignment == style.SH_FormLayoutLabelAlignment
    assert style.StyleHint.SH_ItemView_ArrowKeysNavigateIntoChildren == style.SH_ItemView_ArrowKeysNavigateIntoChildren
    assert style.StyleHint.SH_ComboBox_PopupFrameStyle == style.SH_ComboBox_PopupFrameStyle
    assert style.StyleHint.SH_DialogButtonBox_ButtonsHaveIcons == style.SH_DialogButtonBox_ButtonsHaveIcons
    assert style.StyleHint.SH_ItemView_MovementWithoutUpdatingSelection == style.SH_ItemView_MovementWithoutUpdatingSelection
    assert style.StyleHint.SH_ToolTip_Mask == style.SH_ToolTip_Mask
    assert style.StyleHint.SH_FocusFrame_AboveWidget == style.SH_FocusFrame_AboveWidget
    assert style.StyleHint.SH_TextControl_FocusIndicatorTextCharFormat == style.SH_TextControl_FocusIndicatorTextCharFormat
    assert style.StyleHint.SH_Menu_FlashTriggeredItem == style.SH_Menu_FlashTriggeredItem
    assert style.StyleHint.SH_Menu_FadeOutOnHide == style.SH_Menu_FadeOutOnHide
    assert style.StyleHint.SH_TabWidget_DefaultTabPosition == style.SH_TabWidget_DefaultTabPosition
    assert style.StyleHint.SH_ToolBar_Movable == style.SH_ToolBar_Movable
    assert style.StyleHint.SH_ItemView_PaintAlternatingRowColorsForEmptyArea == style.SH_ItemView_PaintAlternatingRowColorsForEmptyArea
    assert style.StyleHint.SH_Menu_Mask == style.SH_Menu_Mask
    assert style.StyleHint.SH_ItemView_DrawDelegateFrame == style.SH_ItemView_DrawDelegateFrame
    assert style.StyleHint.SH_TabBar_CloseButtonPosition == style.SH_TabBar_CloseButtonPosition
    assert style.StyleHint.SH_DockWidget_ButtonsHaveFrame == style.SH_DockWidget_ButtonsHaveFrame
    assert style.StyleHint.SH_ToolButtonStyle == style.SH_ToolButtonStyle
    assert style.StyleHint.SH_RequestSoftwareInputPanel == style.SH_RequestSoftwareInputPanel
    assert style.StyleHint.SH_ScrollBar_Transient == style.SH_ScrollBar_Transient
    assert style.StyleHint.SH_Menu_SupportsSections == style.SH_Menu_SupportsSections
    assert style.StyleHint.SH_ToolTip_WakeUpDelay == style.SH_ToolTip_WakeUpDelay
    assert style.StyleHint.SH_ToolTip_FallAsleepDelay == style.SH_ToolTip_FallAsleepDelay
    assert style.StyleHint.SH_Widget_Animate == style.SH_Widget_Animate
    assert style.StyleHint.SH_Splitter_OpaqueResize == style.SH_Splitter_OpaqueResize
    assert style.StyleHint.SH_TabBar_ChangeCurrentDelay == style.SH_TabBar_ChangeCurrentDelay
    assert style.StyleHint.SH_ItemView_ScrollMode == style.SH_ItemView_ScrollMode
    assert style.StyleHint.SH_TitleBar_ShowToolTipsOnButtons == style.SH_TitleBar_ShowToolTipsOnButtons
    assert style.StyleHint.SH_Widget_Animation_Duration == style.SH_Widget_Animation_Duration
    assert style.StyleHint.SH_ComboBox_AllowWheelScrolling == style.SH_ComboBox_AllowWheelScrolling
    assert style.StyleHint.SH_SpinBox_ButtonsInsideFrame == style.SH_SpinBox_ButtonsInsideFrame
    assert style.StyleHint.SH_SpinBox_StepModifier == style.SH_SpinBox_StepModifier
    if binding.qt_version_info[:2] >= (6, 1):
        assert style.StyleHint.SH_TabBar_AllowWheelScrolling == style.SH_TabBar_AllowWheelScrolling
    if binding.qt_version_info[:2] >= (6, 3):
        assert style.StyleHint.SH_Table_AlwaysDrawLeftTopGridLines == style.SH_Table_AlwaysDrawLeftTopGridLines

    assert style.StandardPixmap.SP_TitleBarMinButton == style.SP_TitleBarMinButton
    assert style.StandardPixmap.SP_TitleBarMenuButton == style.SP_TitleBarMenuButton
    assert style.StandardPixmap.SP_TitleBarMaxButton == style.SP_TitleBarMaxButton
    assert style.StandardPixmap.SP_TitleBarCloseButton == style.SP_TitleBarCloseButton
    assert style.StandardPixmap.SP_TitleBarNormalButton == style.SP_TitleBarNormalButton
    assert style.StandardPixmap.SP_TitleBarShadeButton == style.SP_TitleBarShadeButton
    assert style.StandardPixmap.SP_TitleBarUnshadeButton == style.SP_TitleBarUnshadeButton
    assert style.StandardPixmap.SP_TitleBarContextHelpButton == style.SP_TitleBarContextHelpButton
    assert style.StandardPixmap.SP_MessageBoxInformation == style.SP_MessageBoxInformation
    assert style.StandardPixmap.SP_MessageBoxWarning == style.SP_MessageBoxWarning
    assert style.StandardPixmap.SP_MessageBoxCritical == style.SP_MessageBoxCritical
    assert style.StandardPixmap.SP_MessageBoxQuestion == style.SP_MessageBoxQuestion
    assert style.StandardPixmap.SP_DesktopIcon == style.SP_DesktopIcon
    assert style.StandardPixmap.SP_TrashIcon == style.SP_TrashIcon
    assert style.StandardPixmap.SP_ComputerIcon == style.SP_ComputerIcon
    assert style.StandardPixmap.SP_DriveFDIcon == style.SP_DriveFDIcon
    assert style.StandardPixmap.SP_DriveHDIcon == style.SP_DriveHDIcon
    assert style.StandardPixmap.SP_DriveCDIcon == style.SP_DriveCDIcon
    assert style.StandardPixmap.SP_DriveDVDIcon == style.SP_DriveDVDIcon
    assert style.StandardPixmap.SP_DriveNetIcon == style.SP_DriveNetIcon
    assert style.StandardPixmap.SP_DirHomeIcon == style.SP_DirHomeIcon
    assert style.StandardPixmap.SP_DirOpenIcon == style.SP_DirOpenIcon
    assert style.StandardPixmap.SP_DirClosedIcon == style.SP_DirClosedIcon
    assert style.StandardPixmap.SP_DirIcon == style.SP_DirIcon
    assert style.StandardPixmap.SP_DirLinkIcon == style.SP_DirLinkIcon
    assert style.StandardPixmap.SP_DirLinkOpenIcon == style.SP_DirLinkOpenIcon
    assert style.StandardPixmap.SP_FileIcon == style.SP_FileIcon
    assert style.StandardPixmap.SP_FileLinkIcon == style.SP_FileLinkIcon
    assert style.StandardPixmap.SP_FileDialogStart == style.SP_FileDialogStart
    assert style.StandardPixmap.SP_FileDialogEnd == style.SP_FileDialogEnd
    assert style.StandardPixmap.SP_FileDialogToParent == style.SP_FileDialogToParent
    assert style.StandardPixmap.SP_FileDialogNewFolder == style.SP_FileDialogNewFolder
    assert style.StandardPixmap.SP_FileDialogDetailedView == style.SP_FileDialogDetailedView
    assert style.StandardPixmap.SP_FileDialogInfoView == style.SP_FileDialogInfoView
    assert style.StandardPixmap.SP_FileDialogContentsView == style.SP_FileDialogContentsView
    assert style.StandardPixmap.SP_FileDialogListView == style.SP_FileDialogListView
    assert style.StandardPixmap.SP_FileDialogBack == style.SP_FileDialogBack
    assert style.StandardPixmap.SP_DockWidgetCloseButton == style.SP_DockWidgetCloseButton
    assert style.StandardPixmap.SP_ToolBarHorizontalExtensionButton == style.SP_ToolBarHorizontalExtensionButton
    assert style.StandardPixmap.SP_ToolBarVerticalExtensionButton == style.SP_ToolBarVerticalExtensionButton
    assert style.StandardPixmap.SP_DialogOkButton == style.SP_DialogOkButton
    assert style.StandardPixmap.SP_DialogCancelButton == style.SP_DialogCancelButton
    assert style.StandardPixmap.SP_DialogHelpButton == style.SP_DialogHelpButton
    assert style.StandardPixmap.SP_DialogOpenButton == style.SP_DialogOpenButton
    assert style.StandardPixmap.SP_DialogSaveButton == style.SP_DialogSaveButton
    assert style.StandardPixmap.SP_DialogCloseButton == style.SP_DialogCloseButton
    assert style.StandardPixmap.SP_DialogApplyButton == style.SP_DialogApplyButton
    assert style.StandardPixmap.SP_DialogResetButton == style.SP_DialogResetButton
    assert style.StandardPixmap.SP_DialogDiscardButton == style.SP_DialogDiscardButton
    assert style.StandardPixmap.SP_DialogYesButton == style.SP_DialogYesButton
    assert style.StandardPixmap.SP_DialogNoButton == style.SP_DialogNoButton
    assert style.StandardPixmap.SP_ArrowUp == style.SP_ArrowUp
    assert style.StandardPixmap.SP_ArrowDown == style.SP_ArrowDown
    assert style.StandardPixmap.SP_ArrowLeft == style.SP_ArrowLeft
    assert style.StandardPixmap.SP_ArrowRight == style.SP_ArrowRight
    assert style.StandardPixmap.SP_ArrowBack == style.SP_ArrowBack
    assert style.StandardPixmap.SP_ArrowForward == style.SP_ArrowForward
    assert style.StandardPixmap.SP_CommandLink == style.SP_CommandLink
    assert style.StandardPixmap.SP_VistaShield == style.SP_VistaShield
    assert style.StandardPixmap.SP_BrowserReload == style.SP_BrowserReload
    assert style.StandardPixmap.SP_BrowserStop == style.SP_BrowserStop
    assert style.StandardPixmap.SP_MediaPlay == style.SP_MediaPlay
    assert style.StandardPixmap.SP_MediaStop == style.SP_MediaStop
    assert style.StandardPixmap.SP_MediaPause == style.SP_MediaPause
    assert style.StandardPixmap.SP_MediaSkipForward == style.SP_MediaSkipForward
    assert style.StandardPixmap.SP_MediaSkipBackward == style.SP_MediaSkipBackward
    assert style.StandardPixmap.SP_MediaSeekForward == style.SP_MediaSeekForward
    assert style.StandardPixmap.SP_MediaSeekBackward == style.SP_MediaSeekBackward
    assert style.StandardPixmap.SP_MediaVolume == style.SP_MediaVolume
    assert style.StandardPixmap.SP_MediaVolumeMuted == style.SP_MediaVolumeMuted
    assert style.StandardPixmap.SP_LineEditClearButton == style.SP_LineEditClearButton
    assert style.StandardPixmap.SP_DialogYesToAllButton == style.SP_DialogYesToAllButton
    assert style.StandardPixmap.SP_DialogNoToAllButton == style.SP_DialogNoToAllButton
    assert style.StandardPixmap.SP_DialogSaveAllButton == style.SP_DialogSaveAllButton
    assert style.StandardPixmap.SP_DialogAbortButton == style.SP_DialogAbortButton
    assert style.StandardPixmap.SP_DialogRetryButton == style.SP_DialogRetryButton
    assert style.StandardPixmap.SP_DialogIgnoreButton == style.SP_DialogIgnoreButton
    assert style.StandardPixmap.SP_RestoreDefaultsButton == style.SP_RestoreDefaultsButton
    if binding.qt_version_info[:2] >= (6, 3):
        assert style.StandardPixmap.SP_TabCloseButton == style.SP_TabCloseButton
    assert style.StandardPixmap.SP_CustomBase == style.SP_CustomBase


def test_qtextframeformat():
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_None == QtGui.QTextFrameFormat.BorderStyle_None
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_Dotted == QtGui.QTextFrameFormat.BorderStyle_Dotted
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_Dashed == QtGui.QTextFrameFormat.BorderStyle_Dashed
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_Solid == QtGui.QTextFrameFormat.BorderStyle_Solid
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_Double == QtGui.QTextFrameFormat.BorderStyle_Double
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_DotDash == QtGui.QTextFrameFormat.BorderStyle_DotDash
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_DotDotDash == QtGui.QTextFrameFormat.BorderStyle_DotDotDash
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_Groove == QtGui.QTextFrameFormat.BorderStyle_Groove
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_Ridge == QtGui.QTextFrameFormat.BorderStyle_Ridge
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_Inset == QtGui.QTextFrameFormat.BorderStyle_Inset
    assert QtGui.QTextFrameFormat.BorderStyle.BorderStyle_Outset == QtGui.QTextFrameFormat.BorderStyle_Outset

    assert QtGui.QTextFrameFormat.PageBreakFlag.PageBreak_Auto == QtGui.QTextFrameFormat.PageBreak_Auto
    assert QtGui.QTextFrameFormat.PageBreakFlag.PageBreak_AlwaysBefore == QtGui.QTextFrameFormat.PageBreak_AlwaysBefore
    assert QtGui.QTextFrameFormat.PageBreakFlag.PageBreak_AlwaysAfter == QtGui.QTextFrameFormat.PageBreak_AlwaysAfter

    assert QtGui.QTextFrameFormat.Position.InFlow == QtGui.QTextFrameFormat.InFlow
    assert QtGui.QTextFrameFormat.Position.FloatLeft == QtGui.QTextFrameFormat.FloatLeft
    assert QtGui.QTextFrameFormat.Position.FloatRight == QtGui.QTextFrameFormat.FloatRight


def test_qtextimageformat():
    assert QtGui.QTextImageFormat.FontPropertiesInheritanceBehavior.FontPropertiesSpecifiedOnly == QtGui.QTextImageFormat.FontPropertiesSpecifiedOnly
    assert QtGui.QTextImageFormat.FontPropertiesInheritanceBehavior.FontPropertiesAll == QtGui.QTextImageFormat.FontPropertiesAll

    assert QtGui.QTextImageFormat.PageBreakFlag.PageBreak_Auto == QtGui.QTextImageFormat.PageBreak_Auto
    assert QtGui.QTextImageFormat.PageBreakFlag.PageBreak_AlwaysBefore == QtGui.QTextImageFormat.PageBreak_AlwaysBefore
    assert QtGui.QTextImageFormat.PageBreakFlag.PageBreak_AlwaysAfter == QtGui.QTextImageFormat.PageBreak_AlwaysAfter

    assert QtGui.QTextImageFormat.UnderlineStyle.NoUnderline == QtGui.QTextImageFormat.NoUnderline
    assert QtGui.QTextImageFormat.UnderlineStyle.SingleUnderline == QtGui.QTextImageFormat.SingleUnderline
    assert QtGui.QTextImageFormat.UnderlineStyle.DashUnderline == QtGui.QTextImageFormat.DashUnderline
    assert QtGui.QTextImageFormat.UnderlineStyle.DotLine == QtGui.QTextImageFormat.DotLine
    assert QtGui.QTextImageFormat.UnderlineStyle.DashDotLine == QtGui.QTextImageFormat.DashDotLine
    assert QtGui.QTextImageFormat.UnderlineStyle.DashDotDotLine == QtGui.QTextImageFormat.DashDotDotLine
    assert QtGui.QTextImageFormat.UnderlineStyle.WaveUnderline == QtGui.QTextImageFormat.WaveUnderline
    assert QtGui.QTextImageFormat.UnderlineStyle.SpellCheckUnderline == QtGui.QTextImageFormat.SpellCheckUnderline

    assert QtGui.QTextImageFormat.VerticalAlignment.AlignNormal == QtGui.QTextImageFormat.AlignNormal
    assert QtGui.QTextImageFormat.VerticalAlignment.AlignSuperScript == QtGui.QTextImageFormat.AlignSuperScript
    assert QtGui.QTextImageFormat.VerticalAlignment.AlignSubScript == QtGui.QTextImageFormat.AlignSubScript
    assert QtGui.QTextImageFormat.VerticalAlignment.AlignMiddle == QtGui.QTextImageFormat.AlignMiddle
    assert QtGui.QTextImageFormat.VerticalAlignment.AlignTop == QtGui.QTextImageFormat.AlignTop
    assert QtGui.QTextImageFormat.VerticalAlignment.AlignBottom == QtGui.QTextImageFormat.AlignBottom
    assert QtGui.QTextImageFormat.VerticalAlignment.AlignBaseline == QtGui.QTextImageFormat.AlignBaseline


def test_qt():
    assert Qt.AlignmentFlag.AlignLeft == Qt.AlignLeft
    assert Qt.AlignmentFlag.AlignRight == Qt.AlignRight
    assert Qt.AlignmentFlag.AlignHCenter == Qt.AlignHCenter
    assert Qt.AlignmentFlag.AlignJustify == Qt.AlignJustify
    assert Qt.AlignmentFlag.AlignTop == Qt.AlignTop
    assert Qt.AlignmentFlag.AlignBottom == Qt.AlignBottom
    assert Qt.AlignmentFlag.AlignVCenter == Qt.AlignVCenter
    assert Qt.AlignmentFlag.AlignBaseline == Qt.AlignBaseline
    assert Qt.AlignmentFlag.AlignCenter == Qt.AlignCenter
    assert Qt.AlignmentFlag.AlignAbsolute == Qt.AlignAbsolute
    assert Qt.AlignmentFlag.AlignLeading == Qt.AlignLeading
    assert Qt.AlignmentFlag.AlignTrailing == Qt.AlignTrailing
    assert Qt.AlignmentFlag.AlignHorizontal_Mask == Qt.AlignHorizontal_Mask
    assert Qt.AlignmentFlag.AlignVertical_Mask == Qt.AlignVertical_Mask

    assert Qt.AnchorPoint.AnchorLeft == Qt.AnchorLeft
    assert Qt.AnchorPoint.AnchorHorizontalCenter == Qt.AnchorHorizontalCenter
    assert Qt.AnchorPoint.AnchorRight == Qt.AnchorRight
    assert Qt.AnchorPoint.AnchorTop == Qt.AnchorTop
    assert Qt.AnchorPoint.AnchorVerticalCenter == Qt.AnchorVerticalCenter
    assert Qt.AnchorPoint.AnchorBottom == Qt.AnchorBottom

    assert Qt.ApplicationState.ApplicationSuspended == Qt.ApplicationSuspended
    assert Qt.ApplicationState.ApplicationHidden == Qt.ApplicationHidden
    assert Qt.ApplicationState.ApplicationInactive == Qt.ApplicationInactive
    assert Qt.ApplicationState.ApplicationActive == Qt.ApplicationActive

    assert Qt.AspectRatioMode.IgnoreAspectRatio == Qt.IgnoreAspectRatio
    assert Qt.AspectRatioMode.KeepAspectRatio == Qt.KeepAspectRatio
    assert Qt.AspectRatioMode.KeepAspectRatioByExpanding == Qt.KeepAspectRatioByExpanding

    assert Qt.GlobalColor.white == Qt.white
    assert Qt.GlobalColor.black == Qt.black
    assert Qt.GlobalColor.red == Qt.red
    assert Qt.GlobalColor.darkRed == Qt.darkRed
    assert Qt.GlobalColor.green == Qt.green
    assert Qt.GlobalColor.darkGreen == Qt.darkGreen
    assert Qt.GlobalColor.blue == Qt.blue
    assert Qt.GlobalColor.darkBlue == Qt.darkBlue
    assert Qt.GlobalColor.cyan == Qt.cyan
    assert Qt.GlobalColor.darkCyan == Qt.darkCyan
    assert Qt.GlobalColor.magenta == Qt.magenta
    assert Qt.GlobalColor.darkMagenta == Qt.darkMagenta
    assert Qt.GlobalColor.yellow == Qt.yellow
    assert Qt.GlobalColor.darkYellow == Qt.darkYellow
    assert Qt.GlobalColor.gray == Qt.gray
    assert Qt.GlobalColor.darkGray == Qt.darkGray
    assert Qt.GlobalColor.lightGray == Qt.lightGray
    assert Qt.GlobalColor.transparent == Qt.transparent
    assert Qt.GlobalColor.color0 == Qt.color0
    assert Qt.GlobalColor.color1 == Qt.color1

    assert Qt.KeyboardModifier.NoModifier == Qt.NoModifier
    assert Qt.KeyboardModifier.ShiftModifier == Qt.ShiftModifier
    assert Qt.KeyboardModifier.ControlModifier == Qt.ControlModifier
    assert Qt.KeyboardModifier.AltModifier == Qt.AltModifier
    assert Qt.KeyboardModifier.MetaModifier == Qt.MetaModifier
    assert Qt.KeyboardModifier.KeypadModifier == Qt.KeypadModifier
    assert Qt.KeyboardModifier.GroupSwitchModifier == Qt.GroupSwitchModifier


def test_qpainter():
    assert QtGui.QPainter.RenderHint.Antialiasing == QtGui.QPainter.Antialiasing
    assert QtGui.QPainter.RenderHint.TextAntialiasing == QtGui.QPainter.TextAntialiasing
    assert QtGui.QPainter.RenderHint.SmoothPixmapTransform == QtGui.QPainter.SmoothPixmapTransform
    if binding.qt_version_info[:2] >= (6, 1):
        assert QtGui.QPainter.RenderHint.VerticalSubpixelPositioning == QtGui.QPainter.VerticalSubpixelPositioning
    assert QtGui.QPainter.RenderHint.LosslessImageRendering == QtGui.QPainter.LosslessImageRendering
    if binding.qt_version_info[:2] >= (6, 4):
        assert QtGui.QPainter.RenderHint.NonCosmeticBrushPatterns == QtGui.QPainter.NonCosmeticBrushPatterns

    assert QtGui.QPainter.PixmapFragmentHint.OpaqueHint == QtGui.QPainter.OpaqueHint
