name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 120
  DISPLAY: ':99.0'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [windows-latest, ubuntu-20.04, macos-latest]
        qt-binding: [PySide6, PyQt6, PySide2, PyQt5]
        exclude:
          - qt-binding: PySide2
            python-version: "3.11"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system packages (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils libgl1-mesa-dev
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade ${{ matrix.qt-binding }}
      #- name: Install pythonnet from a commit (Windows, Python 3.9+)
      #  if: ${{ (matrix.os == 'windows' && (matrix.python-version == '3.9' || matrix.python-version == '3.10')) }}
      #  run: python -m pip install --upgrade git+https://github.com/pythonnet/pythonnet.git@93631aff83b34a0665374cd41313c8552b88b545
      - name: Install package
        run: python -m pip install --upgrade --editable .[tests]
      - name: Run tests
        run: |
          python -c "from msl import qt; print(qt.binding)"
          python -m pytest
