name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [windows, ubuntu, macos]
        qt-binding: [PySide6, PyQt6, PySide2, PyQt5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system packages (Ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 libglvnd-dev \
            libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
            libxcb-randr0 libxcb-render-util0 libxcb-xinerama0
      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade ${{ matrix.qt-binding }}
          python -m pip install --upgrade --editable .[tests]
      - name: Run tests (Ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          python -c "from msl import qt; print(qt.binding)"
          xvfb-run `which python` -m pytest
      - name: Run tests (non Ubuntu)
        if: ${{ matrix.os != 'ubuntu' }}
        run: |
          python -c "from msl import qt; print(qt.binding)"
          python -m pytest
